# Generated by Django 4.2.4 on 2024-04-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='person name')),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=15, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1, verbose_name='gender')),
                ('age', models.SmallIntegerField(verbose_name='age')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('slug', models.SlugField(unique=2, verbose_name='slug')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='weight')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
