# Generated by Django 4.2.4 on 2024-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='person first name')),
                ('middle_name', models.CharField(blank=True, max_length=15, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=15, verbose_name='last name')),
            ],
        ),
    ]
